dataset_params:
  im_path: "/"

diffusion_params:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

model_params:
  in_channels: 3
  in_size: 64
  down_channels: [64, 128, 256, 512]
  mid_channels: [512, 256, 128]
  down_sample: [True, True, False]
  time_emb_dim: 128
  num_layers: 2
  num_heads: 4

training_params:
  batch_size: 64
  learning_rate: 2e-4
  num_epochs: 50
